### ISSUE TITLE
Add Filestash

### ISSUE THREAD

**Issue by mickael-kerjean** [libreprojects/libreprojects#192] opened 2019-12-10 05:52 UTC
Hello,

I've stumbled upon your [website](https://libreprojects.net). I wanted to suggest the [open source project (AGPL) I've been working on](http://github.com/mickael-kerjean/filestash). In a few words, it is a web client that make a range of protocols and platform (FTP, SFTP, GIT, webDAV, ...) look and behave like a Dropbox.

I hope it is worthy of your selection!

Quick links: [code](http://github.com/mickael-kerjean/filestash) - [website](https://www.filestash.app) - [publicly accessible instance](https://demo.filestash.app)

**Comment by jancborchardt** [comment] 2019-12-10 06:10
Hi @mickael-kerjean, very cool project! :) (Cheers from [Nextcloud](https://nextcloud.com)!)

One big requirement for Libre Projects as per the [readme](https://github.com/libreprojects/libreprojects#libre-projects) is:

> **web-based & hosted** and with a gratis plan

This is so people who are not technical can just readily use the software.

It seems Filestash does not fit that by design, as you have to put it on your own FTP / S3 / etc. – and as such have something like that (and know what it is) in the first place?

**Comment by mickael-kerjean** [comment] 2019-12-10 06:48
> One big requirement .... web-based & hosted and with a gratis plan

- [X] `web-based`
- [X] `hosted`: https://www.filestash.app/pricing/
- [X] `with a gratis plan`: there's a publicly accessible instance that's gratis: https://demo.filestash.app/login

> not technical can just readily use the software.

That's the entire point of Filestash: making traditional platform/protocols easy to use (see my [own instance](https://files.kerjean.me/login)) when every other FTP clients are built with the technical user in mind.

> does not fit that by design, as you have to put it on your own FTP / S3 / etc

I wouldn't say opening an account on github or gitlab requires much technical skills. Plus I coudn't find another tool that makes git as easy to use: https://demo.filestash.app/login?next=/view/org/emacs.org#type=git&repo=https://github.com/mickael-kerjean/nuage_org_demo

> your own FTP / S3 / etc

Somehow the data needs to get stored somewhere but it doesn't necessarily has to be controlled by the user: Eg: mirrors in most of the linux distribution and many software projects still use FTP. Eg: https://wiki.archlinux.org/index.php/mirrors, ftp.vim.org, ...

**Comment by jancborchardt** [comment] 2019-12-10 07:35
Aaah ok, https://demo.filestash.app/login makes sense! From the https://demo.filestash.app page it only looked like a demo instance with example files, and I didn’t think about clicking the "Power on/off" icon to log in to something. :)

I’d say if you like you can add it as per the guidelines at https://github.com/libreprojects/libreprojects#adding-new-projects

What do the other @libreprojects/contributors think?

**Comment by ironbishop** [comment] 2019-12-10 10:57
It's a great project, seems ok to have it listed. 👍

**Comment by lucab** [comment] 2020-01-08 13:50
Closed by #193.

**Closed as completed by lucab** 2020-01-08 13:50 UTC
